### ISSUE TITLE
[Testground Infra] Error in kube-controller-manager when starting cluster

### ISSUE THREAD

**Issue by adlrocha** [testground/testground#1139]
#### Version information:
Infra repo version: https://github.com/testground/infra/commit/3dc3a022216c330999fb4680b1a7a14324b25a23

#### Description:
When running `./k8s/install.sh ./k8s/cluster.yaml` to start a Testground cluster the script times out in kops validation.
```
VALIDATION ERRORS
KIND            NAME                                                                                    MESSAGE
ComponentStatus controller-manager                                                                      component "controller-manager" is unhealthy
Machine         i-0147ccef98bf25706                                                                     machine "i-0147ccef98bf25706" has not yet joined cluster
Machine         i-03b1081554515aff5                                                                     machine "i-03b1081554515aff5" has not yet joined cluster
Machine         i-045c57750d1be47ec                                                                     machine "i-045c57750d1be47ec" has not yet joined cluster
Machine         i-04f62604d0c9df4e6                                                                     machine "i-04f62604d0c9df4e6" has not yet joined cluster
Machine         i-09c5785bdc6e1f6e2                                                                     machine "i-09c5785bdc6e1f6e2" has not yet joined cluster
Machine         i-0bf48332714f926f9                                                                     machine "i-0bf48332714f926f9" has not yet joined cluster
Machine         i-0ce10d921ced32c05                                                                     machine "i-0ce10d921ced32c05" has not yet joined cluster
Pod             kube-system/etcd-manager-events-ip-172-20-61-229.eu-central-1.compute.internal          system-cluster-critical pod "etcd-manager-events-ip-172-20-61-229.eu-central-1.compute.internal" is pending
Pod             kube-system/etcd-manager-main-ip-172-20-61-229.eu-central-1.compute.internal            system-cluster-critical pod "etcd-manager-main-ip-172-20-61-229.eu-central-1.compute.internal" is pending
Pod             kube-system/kube-apiserver-ip-172-20-61-229.eu-central-1.compute.internal               system-cluster-critical pod "kube-apiserver-ip-172-20-61-229.eu-central-1.compute.internal" is pending
Pod             kube-system/kube-controller-manager-ip-172-20-61-229.eu-central-1.compute.internal      system-cluster-critical pod "kube-controller-manager-ip-172-20-61-229.eu-central-1.compute.internal" is pending
Pod             kube-system/kube-proxy-ip-172-20-61-229.eu-central-1.compute.internal                   system-node-critical pod "kube-proxy-ip-172-20-61-229.eu-central-1.compute.internal" is pending
Pod             kube-system/kube-scheduler-ip-172-20-61-229.eu-central-1.compute.internal               system-cluster-critical pod "kube-scheduler-ip-172-20-61-229.eu-central-1.compute.internal" is pending
Validation Failed
W0915 13:51:41.611597  159930 validate_cluster.go:221] (will retry): cluster not yet healthy
Validation failed: wait time exceeded during validation
Error on line 59
```
If we ssh the instances we see the following error in the `kube-controller-manager` of the master node:
```
I0915 12:09:41.917392       1 flags.go:33] FLAG: --v="2"
I0915 12:09:41.917395       1 flags.go:33] FLAG: --version="false"
I0915 12:09:41.917402       1 flags.go:33] FLAG: --vmodule=""
I0915 12:09:42.482952       1 serving.go:313] Generated self-signed cert in-memory
W0915 12:09:42.853326       1 authentication.go:410] failed to read in-cluster kubeconfig for delegated authentication: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
W0915 12:09:42.853353       1 authentication.go:268] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0915 12:09:42.853359       1 authentication.go:292] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0915 12:09:42.853367       1 authorization.go:177] failed to read in-cluster kubeconfig for delegated authorization: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
W0915 12:09:42.853375       1 authorization.go:146] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
I0915 12:09:42.853387       1 controllermanager.go:161] Version: v1.18.3
I0915 12:09:42.854100       1 tlsconfig.go:200] loaded serving cert ["Generated self signed cert"]: "localhost@1600171782" [serving] validServingFor=[127.0.0.1,localhost,localhost] issuer="localhost-ca@1600171782" (2020-09-15 11:09:41 +0000 UTC to 2021-09-15 11:09:41 +0000 UTC (now=2020-09-15 12:09:42.854087925 +0000 UTC))
I0915 12:09:42.854239       1 named_certificates.go:53] loaded SNI cert [0/"self-signed loopback"]: "apiserver-loopback-client@1600171782" [serving] validServingFor=[apiserver-loopback-client] issuer="apiserver-loopback-client-ca@1600171782" (2020-09-15 11:09:42 +0000 UTC to 2021-09-15 11:09:42 +0000 UTC (now=2020-09-15 12:09:42.854232795 +0000 UTC))
I0915 12:09:42.854264       1 secure_serving.go:178] Serving securely on [::]:10257
I0915 12:09:42.854342       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0915 12:09:42.854733       1 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
I0915 12:09:42.854771       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/kube-controller-manager...
I0915 12:09:58.812712       1 leaderelection.go:252] successfully acquired lease kube-system/kube-controller-manager
I0915 12:09:58.812737       1 event.go:278] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"2974d19c-5d49-4479-b23c-316b8173729a", APIVersion:"v1", ResourceVersion:"766", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-172-20-41-35_9c4553e8-d38d-49a7-a712-9534ce6853d3 became leader
I0915 12:09:58.812763       1 event.go:278] Event(v1.ObjectReference{Kind:"Lease", Namespace:"kube-system", Name:"kube-controller-manager", UID:"6c66788f-6e09-434d-834f-cd2e943bc70d", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"767", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-172-20-41-35_9c4553e8-d38d-49a7-a712-9534ce6853d3 became leader
I0915 12:09:58.814114       1 controllermanager.go:217] using legacy client builder
W0915 12:09:58.821791       1 plugins.go:115] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
I0915 12:09:58.821952       1 aws.go:1214] Building AWS cloudprovider
I0915 12:09:58.821992       1 aws.go:1180] Zone not specified in configuration file; querying AWS metadata service
I0915 12:09:58.957313       1 tags.go:79] AWS cloud filtering on ClusterID: adlrocha.k8s.local
I0915 12:09:58.957333       1 aws.go:771] Setting up informers for Cloud
I0915 12:09:58.957946       1 shared_informer.go:223] Waiting for caches to sync for tokens
I0915 12:09:58.958113       1 reflector.go:175] Starting reflector *v1.ServiceAccount (16h5m31.590033723s) from k8s.io/client-go/informers/factory.go:135
I0915 12:09:58.958116       1 reflector.go:175] Starting reflector *v1.Node (16h5m31.590033723s) from k8s.io/client-go/informers/factory.go:135
I0915 12:09:58.958173       1 reflector.go:175] Starting reflector *v1.Secret (16h5m31.590033723s) from k8s.io/client-go/informers/factory.go:135
I0915 12:09:58.959741       1 reflector.go:175] Starting reflector *v1.Secret (0s) from k8s.io/client-go/tools/watch/informerwatcher.go:146
I0915 12:09:59.058114       1 shared_informer.go:230] Caches are synced for tokens
I0915 12:10:28.959830       1 reflector.go:181] Stopping reflector *v1.Secret (0s) from k8s.io/client-go/tools/watch/informerwatcher.go:146
F0915 12:10:28.959860       1 client_builder.go:238] unable to get token for service account: timed out waiting for the condition
goroutine 221 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0xc000549700, 0xc0000f0380, 0x82, 0xdf)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:875 +0xb8
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x6d09860, 0xc000000003, 0xc0008d7b90, 0x6bca1e8, 0x11, 0xee, 0x0)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:826 +0x330
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printDepth(0x6d09860, 0x3, 0x1, 0xc000dc4c80, 0x1, 0x1)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:698 +0x129
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).print(...)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:689
k8s.io/kubernetes/vendor/k8s.io/klog.Fatal(...)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1256
k8s.io/kubernetes/pkg/controller.SAControllerClientBuilder.ClientOrDie(0xc0005e9200, 0x4984e60, 0xc000410d00, 0x48a3a20, 0xc000410c10, 0x4143189, 0xb, 0x415916f, 0x12, 0x32f4251, ...)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/client_builder.go:238 +0xfd
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/aws.(*Cloud).Initialize(0xc000992c80, 0x7f7520302fd8, 0xc000423500, 0xc000b8c7e0)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/aws/aws.go:1357 +0x6a
k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers(0x48ff520, 0xc000423500, 0x498fcc0, 0xc000099db0, 0x489a720, 0xc000b5b240, 0x0, 0x0, 0x0, 0x0, ...)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:507 +0x7e7
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func1(0x48fdca0, 0xc000422bc0)
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:234 +0x58d
created by k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
        /workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:207 +0x132
```
It is potentially an error in the version of kubernetes used by kops.

**Comment by nonsense** [comment]
Thanks for reporting @adlrocha .

I am not sure if this is a permanent error or a transient one. @adlrocha I will try to create a cluster later today and tomorrow and report back if I get the same behaviour as the one we observed with you.

I am not sure what is the reason for:
```
F0915 12:10:28.959860       1 client_builder.go:238] unable to get token for service account: timed out waiting for the condition
```

For the benefit of other users - it appears `kops` fails to create even a vanilla cluster at the moment. As a first step we could try to upgrade our dependencies (kops, Kubernetes, etc.) and try again.

**Comment by nonsense** [comment]
I tried creating a cluster, and it worked fine with:

```
kops version
Version 1.18.0-beta.1 (git-ec8022b352)
```

This means that either something changed on `kops` side or this is a transient error. Will try the latest stable version of `kops` and report back.

**Comment by nonsense** [comment]
I tried with the latest stable `kops` version, and it worked fine again:

```
kops version
Version 1.18.1 (git-453d7d96be)
```

---

I had the same docker image for the kube-controller:
```
5d1d9afc182f        da26705ccb4b                      "/usr/local/bin/kube…"   17 minutes ago      Up 17 minutes                           k8s_kube-controller-manager_kube-controller-manager-ip-172-20-57-216.eu-west-2.compute.internal_kube-system_c54a863cd76944eced186189d0032ef4_0
```

It looks like this was a transient error.

**Comment by adlrocha** [comment]
Confirmed! It worked for me. It was a transient error. Thanks @nonsense!

**Comment by adlrocha** [comment]
Sorry I have to open it again, but after briefly getting it to work yesterday, today I didn't manage to make the cluster spawn after several attempts. Still getting the same error from above:

https://github.com/testground/testground/issues/1139#issue-701936619
