### ISSUE TITLE
tasks page isn't working when starting daemon from a non-project-root directory 

### ISSUE THREAD

**Issue by huiscool** [testground/testground#1220]
#### Version information:

commit be5f89d28d3d38bdc279a455657abcfd4760b2ab

macOS Big Sur Version 11.2.2
#### Description:

**What you were doing when you experienced the bug:**
I start the testground deamon from a directory that is not the testground code root. Say that `~/code/testground` is the directory where I cloned the testground code, and `make install` has been run. Then I start daemon from `~` or `~/testground`, open `localhost:8042/tasks` in my browser, and I get:
![image](https://user-images.githubusercontent.com/30804350/115183419-4be75d00-a10e-11eb-9c93-bf40464202e1.png)
**Any error messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas)**
The log in daemon says:
```
2021/04/19 12:53:39 http: panic serving 127.0.0.1:58012: cannot ParseFiles with tmpl/tasks: open tmpl/tasks.html: no such file or directory
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc0000cf860)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x25cf340, 0xc0000a9b60)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/testground/testground/pkg/daemon.(*Daemon).listTasksHandler.func1(0x2b53500, 0xc000022000, 0xc000124200)
	/Users/huyingcong/code/testground/pkg/daemon/tasks.go:142 +0x1671
net/http.HandlerFunc.ServeHTTP(0xc00000ee00, 0x2b53500, 0xc000022000, 0xc000124200)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/testground/testground/pkg/daemon.New.func2.1(0x2b53500, 0xc000022000, 0xc000124200)
	/Users/huyingcong/code/testground/pkg/daemon/daemon.go:76 +0x14f
net/http.HandlerFunc.ServeHTTP(0xc0004c0100, 0x2b53500, 0xc000022000, 0xc000124200)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004ac0c0, 0x2b53500, 0xc000022000, 0xc000124000)
	/Users/huyingcong/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xd3
net/http.serverHandler.ServeHTTP(0xc00018c000, 0x2b53500, 0xc000022000, 0xc000124000)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0000cf860, 0x2b58540, 0xc00004c100)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```
However, when I start the daemon from `~/code/testground`, I get the expected page.

This may be caused by the incorrent relative path in `pkg/daemon/task.go:140`:
```
		t, err = t.ParseFiles("tmpl/tasks.html")
		if err != nil {
			panic(fmt.Sprintf("cannot ParseFiles with tmpl/tasks: %s", err))
		}
```

**Comment by brdji** [comment]
We have merged a fix which will be live in the next release.
