### ISSUE TITLE
interface conversion panic on TaaS

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1224]
```
May  7 18:42:54.452312  DEBUG   queue.pop       {"len": 36}
May  7 18:42:54.452323  DEBUG   queue.pop.got-task      {"id": "c2ae9555p7ad220paglg", "testname": "lotus-soup:deals-e2e"}
May  7 18:42:54.452276  INFO    supervisor worker started       {"worker_id": 5}
May  7 18:42:54.452162  INFO    supervisor worker started       {"worker_id": 0}
May  7 18:42:54.452175  INFO    supervisor worker started       {"worker_id": 3}
May  7 18:42:54.452452  INFO    listen and serve        {"addr": "[::]:8042"}
May  7 18:42:54.452473  INFO    daemon listening        {"addr": "[::]:8042"}
May  7 18:42:54.452532  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452543  DEBUG   queue.pop       {"len": 35}
May  7 18:42:54.452547  DEBUG   queue.pop.got-task      {"id": "c2ae96t5p7ad220pagm0", "testname": "lotus-soup:paych-stress"}
May  7 18:42:54.452572  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452579  DEBUG   queue.pop       {"len": 34}
May  7 18:42:54.452582  DEBUG   queue.pop.got-task      {"id": "c2ae9755p7ad220pagmg", "testname": "lotus-soup:paych-stress"}
May  7 18:42:54.452603  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452605  DEBUG   queue.pop       {"len": 33}
May  7 18:42:54.452614  DEBUG   queue.pop.got-task      {"id": "c2ae9755p7ad220pagn0", "testname": "lotus-soup:deals-e2e"}
May  7 18:42:54.452684  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452692  DEBUG   queue.pop       {"len": 32}
May  7 18:42:54.452697  DEBUG   queue.pop.got-task      {"id": "c2ael3d5p7ad220pagng", "testname": "lotus-soup:paych-stress"}
May  7 18:42:54.452728  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452735  DEBUG   queue.pop       {"len": 31}
May  7 18:42:54.452739  DEBUG   queue.pop.got-task      {"id": "c2af02l5p7ad220pago0", "testname": "lotus-soup:deals-e2e"}
May  7 18:42:54.452776  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452782  DEBUG   queue.pop       {"len": 30}
May  7 18:42:54.452787  DEBUG   queue.pop.got-task      {"id": "c2af0355p7ad220pagog", "testname": "lotus-soup:paych-stress"}
May  7 18:42:54.452830  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452837  DEBUG   queue.pop       {"len": 29}
May  7 18:42:54.452841  DEBUG   queue.pop.got-task      {"id": "c2af3jd5p7ad220pagp0", "testname": "lotus-soup:paych-stress"}
May  7 18:42:54.452874  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452880  DEBUG   queue.pop       {"len": 28}
May  7 18:42:54.452884  DEBUG   queue.pop.got-task      {"id": "c2af49d5p7ad220pagpg", "testname": "lotus-soup:deals-e2e"}
May  7 18:42:54.452919  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452925  DEBUG   queue.pop       {"len": 27}
May  7 18:42:54.452930  DEBUG   queue.pop.got-task      {"id": "c2af4dd5p7ad220pagq0", "testname": "lotus-soup:deals-e2e"}
May  7 18:42:54.452954  ERROR   error while popping task from the queue {"err": "leveldb: not found"}
May  7 18:42:54.452960  DEBUG   queue.pop       {"len": 26}
May  7 18:42:54.452965  DEBUG   queue.pop.got-task      {"id": "c2aji0l5p7ad220pagqg", "testname": "lotus-soup:deals-e2e"}
May  7 18:42:54.456967  DEBUG   queue.pop       {"len": 25}
May  7 18:42:54.456983  DEBUG   queue.pop.got-task      {"id": "c2aji1l5p7ad220pagr0", "testname": "lotus-soup:deals-e2e"}
May  7 18:42:54.461005  DEBUG   queue.pop       {"len": 24}
May  7 18:42:54.461024  DEBUG   queue.pop.got-task      {"id": "c2aji2l5p7ad220pagrg", "testname": "lotus-soup:paych-stress"}
May  7 18:42:54.462700  INFO    worker processing task  {"worker_id": 4, "task_id": "c2aji0l5p7ad220pagqg"}
panic: interface conversion: interface {} is map[string]interface {}, not *engine.RunInput

goroutine 14 [running]:
github.com/testground/testground/pkg/engine.(*Engine).worker.func1(0xc000919cd8, 0xc0001b5c70, 0xc0000b6400, 0xc000919cf0, 0x4)
        /pkg/engine/supervisor.go:115 +0x1799
github.com/testground/testground/pkg/engine.(*Engine).worker(0xc0001b5c70, 0x4)
        /pkg/engine/supervisor.go:181 +0x2d1
created by github.com/testground/testground/pkg/engine.NewEngine
        /pkg/engine/engine.go:121 +0x5d9
```

**Comment by brdji** [comment]
I believe a found a way to reproduce this locally:
1. Start the testground daemon
2. Run a test case that takes a while to complete, e.g. using the learning-example project:
```
testground run single --plan tg-learning --testcase tg-sync-manyto1 --builder docker:generic --runner local:docker --instances 2
```
3. While the test case is running, try to run the test case two more times (ie. repeat the same command).
4. Stop the testground daemon
5. Start the testground daemon again, and the error should appear

**Comment by brdji** [comment]
The cause of the issue seems to lie in the JSON marshaling / unmarshaling when a task is persisted to the DB. An easy way to reproduce this issue is to add the following lines to the `engine.go` file, `QueueRun` function:
```
// task created from the api runRequest 
var newTask = &task.Task{
		Version:     0,
		Priority:    request.Priority,
...
}

// convert the newly created task to JSON and back
convertedTask := &task.Task{}
val, err := json.Marshal(newTask)
err = json.Unmarshal(val, convertedTask)

// try to push it to the engine queue
err = e.queue.Push(convertedTask)
```
Attempting to run any test case will now trigger the same error.

Any ideas why the JSON conversion process seems to cause these issues?
