### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vgiotsas** [testground/testground#1423]
#### Version information:
commit 775a58896b01063ae7d9fef0afbb4faf7a5f2bf5

Ubuntu 20.04.4 LTS, Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GH, 64 bit
go version go1.16.7 linux/amd64
Docker version 20.10.17, build 100c701

#### Description:

When trying to execute the ping-pong test case I get the following error:

```
$ ~/go/bin/testground run single \
>          --plan=network \
>          --testcase=ping-pong \
>          --builder=docker:go \
>          --runner=local:docker \
>          --instances=2

Aug 13 22:14:51.159991	INFO	created a synthetic composition file for this job; all instances will run under singleton group "single"
Aug 13 22:14:51.160031	INFO	using home directory: /home/giotsas/testground
Aug 13 22:14:51.160111	INFO	.env.toml loaded from: /home/giotsas/testground/.env.toml
Aug 13 22:14:51.160121	INFO	testground client initialized	{"addr": "127.0.0.1:8080"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8bd126]

goroutine 1 [running]:
net/http.(*Request).WithContext(...)
	/usr/local/go/src/net/http/request.go:359
github.com/testground/testground/pkg/client.(*Client).request(0xc0003cc200, 0x2466300, 0xc0003c4080, 0x20b90dd, 0x4, 0x20b8a51, 0x4, 0x2429460, 0xc0006a2340, 0xc00099f220, ...)
	/home/giotsas/testground/pkg/client/client.go:522 +0x146
github.com/testground/testground/pkg/client.(*Client).runBuild(0xc0003cc200, 0x2466300, 0xc0003c4080, 0x1cc8e20, 0xc000540000, 0x20b8a51, 0x4, 0xc0009e55c0, 0x26, 0x0, ...)
	/home/giotsas/testground/pkg/client/client.go:221 +0x43f
github.com/testground/testground/pkg/client.(*Client).Run(...)
	/home/giotsas/testground/pkg/client/client.go:68
github.com/testground/testground/pkg/cmd.run(0xc00081b780, 0xc000787810, 0x0, 0x0)
	/home/giotsas/testground/pkg/cmd/run.go:268 +0x60a
github.com/testground/testground/pkg/cmd.runSingleCmd(0xc00081b780, 0x13, 0x24)
	/home/giotsas/testground/pkg/cmd/run.go:191 +0x119
github.com/urfave/cli/v2.(*Command).Run(0x3157a40, 0xc00081b000, 0x0, 0x0)
	/home/giotsas/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc00031d520, 0xc00081af40, 0x0, 0x0)
	/home/giotsas/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xa49
github.com/urfave/cli/v2.(*Command).startApp(0x3158340, 0xc00081af40, 0x7fff2ffc16dd, 0x3)
	/home/giotsas/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x69b
github.com/urfave/cli/v2.(*Command).Run(0x3158340, 0xc00081af40, 0x0, 0x0)
	/home/giotsas/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x98d
github.com/urfave/cli/v2.(*App).RunContext(0xc00031d380, 0x2466338, 0xc000040058, 0xc00003c080, 0x8, 0x8, 0x0, 0x0)
	/home/giotsas/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/home/giotsas/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/giotsas/testground/main.go:30 +0x159
```

The `testground daemon` runs normally, but doesn't show any error:

```
$ ~/go/bin/testground daemon
Aug 13 22:13:35.716811	INFO	using home directory: /home/giotsas/testground
Aug 13 22:13:35.744385	INFO	.env.toml loaded from: /home/giotsas/testground/.env.toml
Aug 13 22:13:35.756132	INFO	listen and serve	{"addr": "[::]:8080"}
Aug 13 22:13:35.756168	INFO	daemon listening	{"addr": "[::]:8080"}
Aug 13 22:13:35.755632	INFO	supervisor worker started	{"worker_id": 1}
Aug 13 22:13:35.755638	INFO	supervisor worker started	{"worker_id": 0}

```

My `$TESTGROUND_HOME/.env.toml` is:

```
[daemon]
listen = ":8080"

[client]
endpoint = "127.0.0.1:8080"
```

**Comment by laurentsenta** [comment]
Hi @vgiotsas it looks like the client cannot submit the test to your daemon,

- What happens if you run `nc 127.0.0.1 8080`, type some text and press enter?
- Can you open http://localhost:8080 on your browser?

**Comment by vgiotsas** [comment]
Thanks a lot @laurentsenta 
Your response pointed me to the right direction and I resolved the issue
