### ISSUE TITLE
EKS: unable to determine data network IP

### ISSUE THREAD

**Issue by ackintosh** [testground/testground#1563]
## Version information:

The latest ([006cfaa](https://github.com/testground/infra/commit/006cfaab660d22717e995c991756101ac75ca9f2)) install script in [testground/infra](https://github.com/testground/infra/tree/master/k8s/eks). (EKS)

## Description:

I have setup EKS cluster with [the install script](https://github.com/testground/infra/blob/master/k8s/eks/testground_install.sh). That seems successful but I got the `unable to determine data network IP` error when I run [`pingpong`](https://github.com/testground/testground/blob/master/plans/network/pingpong.go) test plan.

#### Setup EKS cluster

```shell
# Setup EKS cluster
$ ./testground_install.sh
...
...
...

Your cluster is ready to be used.

tar: Removing leading '/' from member names
========================
Log file generated with name 2023-01-09-13:59:35-gossipsub.tar.gz

# Make sure the deployments are READY
$ kubectl get deployments
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
efs-provisioner           1/1     1            1           54m
influxdb                  1/1     1            1           53m
testground-daemon         1/1     1            1           53m
testground-sync-service   1/1     1            1           53m
```

#### Run `pingpong` 

```shell
$ testground run single --plan network --testcase ping-pong --builder docker:go --runner cluster:k8s --instances 2

...
...
...
Jan  9 05:57:57.463190  DEBUG   testplan pods state     {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "running_for": "12s", "succeeded": 0, "running": 2, "pending": 0, "failed": 0, "unknown": 0}
Jan  9 05:57:59.498623  DEBUG   testplan pods state     {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "running_for": "14s", "succeeded": 2, "running": 0, "pending": 0, "failed": 0, "unknown": 0}
Jan  9 05:57:59.498702  INFO    all testplan instances in `Succeeded` state     {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "took": "14s"}
Jan  9 05:57:59.498772  INFO    cleaning up finished pods...    {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg"}
Jan  9 05:57:59.498846  DEBUG   fetching logs   {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "pod": "tg-network-cetqod126unb9qan1jcg-single-1"}
Jan  9 05:57:59.498847  DEBUG   fetching logs   {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "pod": "tg-network-cetqod126unb9qan1jcg-single-0"}
Jan  9 05:57:59.532211  DEBUG   got logs        {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "pod": "tg-network-cetqod126unb9qan1jcg-single-0", "len": 7707}
Jan  9 05:57:59.538430  DEBUG   got logs        {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "pod": "tg-network-cetqod126unb9qan1jcg-single-1", "len": 7708}
Jan  9 05:57:59.538512  DEBUG   done getting logs       {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg"}
Jan  9 05:57:59.538523  DEBUG   deleting pod    {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "pod": "tg-network-cetqod126unb9qan1jcg-single-1"}
Jan  9 05:57:59.567065  DEBUG   deleting pod    {"runner": "cluster:k8s", "run_id": "cetqod126unb9qan1jcg", "pod": "tg-network-cetqod126unb9qan1jcg-single-0"}
Jan  9 05:57:59.592405  INFO    run finished with outcome = failure (single:0/2)        {"run_id": "cetqod126unb9qan1jcg", "plan": "network", "case": "ping-pong", "runner": "cluster:k8s", "instances": 2}
Jan  9 05:57:59.602969  INFO    worker completed task   {"worker_id": 0, "task_id": "cetqod126unb9qan1jcg"}
```

#### `unable to determine data network IP`

```shell
$ less cetqod126unb9qan1jcg/single/0/run.err

unable to determine data network IP. no interface found with IP in 10.32.1.2/15
goroutine 1 [running]:
runtime/debug.Stack(0x50, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/testground/sdk-go/run.invoke.func3(0xc000204340)
        /go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:151 +0xbe
panic(0x94f920, 0xc00038e1c0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/testground/sdk-go/run.invoke(0xc000204340, 0x949720, 0xa17d10)
        /go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:191 +0x6c7
github.com/testground/sdk-go/run.InvokeMap(0xc000216030)
        /go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:77 +0xa9
main.main()
        /plan/main.go:15 +0x2d
```

**Comment by ackintosh** [comment]
FYI: `run.out`

```shell
$ cat cetqod126unb9qan1jcg/single/0/run.out

{"ts":1673243874227436937,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"registering default http handler at: http://[::]:6060/ (pprof: http://[::]:6060/debug/pprof/)"}}}
{"ts":1673243874227471045,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"start_event":{"runenv":{"plan":"network","case":"ping-pong","run":"cetqod126unb9qan1jcg","params":{},"instances":2,"outputs_path":"/outputs/cetqod126unb9qan1jcg/single/0","temp_path":"","network":"10.32.0.0/12","group":"single","group_instances":2}}}}
{"ts":1673243874238713123,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"waiting for network to initialize"}}}
{"ts":1673243876617517151,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"network initialisation successful"}}}
{"ts":1673243876617900296,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"network initialization complete"}}}
{"ts":1673243876618504059,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"claimed sequence numbers; global=2, group(single)=2"}}}
{"ts":1673243876618518688,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"before sync.MustBoundClient"}}}
{"ts":1673243876618606341,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"before netclient.MustConfigureNetwork"}}}
{"ts":1673243876719801825,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"I am 2"}}}
{"ts":1673243876719815809,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"before reconfiguring network"}}}
{"ts":1673243877059817925,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"127.0.0.1 not in data subnet 10.32.1.2/15, ignoring"}}}
{"ts":1673243877059870059,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"192.168.78.24 not in data subnet 10.32.1.2/15, ignoring"}}}
{"ts":1673243877059895521,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"message_event":{"message":"10.46.0.2 not in data subnet 10.32.1.2/15, ignoring"}}}
{"ts":1673243877059948979,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"crash_event":{"group":"single","error":"goroutine 47 [running]:\nruntime/debug.Stack(0xc000183af0, 0x94f920, 0xc00038e1c0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/testground/sdk-go/run.HandlePanics()\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/panic.go:23 +0x55\npanic(0x94f920, 0xc00038e1c0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/testground/sdk-go/network.(*Client).MustGetDataNetworkIP(...)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/network/address.go:58\nmain.pingpong(0xc000204340, 0xc000216ff0, 0x0, 0x0)\n\t/plan/pingpong.go:84 +0xf93\ngithub.com/testground/sdk-go/run.invoke.func4(0xc0002187e0, 0x949720, 0xa17d10, 0xc000204340, 0xc000234100)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:173 +0x1d6\ncreated by github.com/testground/sdk-go/run.invoke\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:162 +0x4e5\n","stacktrace":"goroutine 1 [running]:\nruntime/debug.Stack(0x9f1b61, 0x2, 0xc000187c88)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/testground/sdk-go/runtime.(*RunEnv).RecordCrash(0xc000204340, 0x936140, 0xc00038e1d0)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/runtime/runenv_events.go:246 +0xa5\ngithub.com/testground/sdk-go/run.invoke(0xc000204340, 0x949720, 0xa17d10)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:190 +0x6ac\ngithub.com/testground/sdk-go/run.InvokeMap(0xc000216030)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:77 +0xa9\nmain.main()\n\t/plan/main.go:15 +0x2d\n"}}}
{"ts":1673243877061147400,"msg":"","group_id":"single","run_id":"cetqod126unb9qan1jcg","event":{"crash_event":{"group":"single","error":"unable to determine data network IP. no interface found with IP in 10.32.1.2/15","stacktrace":"goroutine 1 [running]:\nruntime/debug.Stack(0x9f1b61, 0x2, 0xc0004ffa78)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/testground/sdk-go/runtime.(*RunEnv).RecordCrash(0xc000204340, 0x94f920, 0xc00038e1c0)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/runtime/runenv_events.go:246 +0xa5\ngithub.com/testground/sdk-go/run.invoke.func3(0xc000204340)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:147 +0x65\npanic(0x94f920, 0xc00038e1c0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/testground/sdk-go/run.invoke(0xc000204340, 0x949720, 0xa17d10)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:191 +0x6c7\ngithub.com/testground/sdk-go/run.InvokeMap(0xc000216030)\n\t/go/pkg/mod/github.com/testground/sdk-go@v0.3.1-0.20211012114808-49c90fa75405/run/invoker.go:77 +0xa9\nmain.main()\n\t/plan/main.go:15 +0x2d\n"}}}
```

**Comment by ackintosh** [comment]
> unable to determine data network IP. no interface found with IP in 10.32.1.2/15

I found the ip address translation in `ping-pong`. I think this is relates to the issue.

https://github.com/testground/testground/blob/3400b0e10b58ba772f3a1a1c37f2c73fbc0e1972/plans/network/pingpong.go#L63-L64

**Comment by laurentsenta** [comment]
@ackintosh, thanks for raising this,

The [Must Configure Network](https://github.com/testground/testground/blob/3400b0e10b58ba772f3a1a1c37f2c73fbc0e1972/plans/network/pingpong.go#L82) requests an IP change for the current instance, it seems like the SDK panics in the `MustGetDataNetworkIP` below because the new IP (`10.46.0.2` doesn't match the expected subnet).

- does it happens every time you run that test?
- could you log the instance IP before [must configure network changes the IP](https://github.com/testground/testground/blob/3400b0e10b58ba772f3a1a1c37f2c73fbc0e1972/plans/network/pingpong.go#L82)?

@sysrex have you seen this case when you worked on EKS?
