### ISSUE TITLE
dht test panic

### ISSUE THREAD

**Issue by nonsense** [testground/testground#853]
While working on the DHT testplan with sync service v2, we came across this panic, which looks irrelevant to the sync service. @aschmahmann any ideas?

```
testground run composition -f ./compositions/all-cypress-k8s.toml --collect
```

```
{"ts":1586971298427370699,"msg":"","group_id":"cypress-searcher","run_id":"13892111c6c8","event":{"type":"metric","metric":{"name":"full ipns-records9","unit":"ns","dir":-1,"value":2000540388}}}
{"ts":1586971298427437203,"msg":"","group_id":"cypress-searcher","run_id":"13892111c6c8","event":{"type":"message","message":"Searching for IPNS Key: /ipns/\u0000$\u0008\u0001\u0012 u\ufffd}\u0019˸\ufffd\ufffd\ufffdT^\ufffd\ufffd\u0015\ufffdY\ufffdt?U/\ufffd\ufffd\ufffd#\ufffd\ufffdYzc\u001d\u0004"}}
{"ts":1586971298427453860,"msg":"","group_id":"cypress-searcher","run_id":"13892111c6c8","event":{"type":"message","message":"Searching for IPNS Key: /ipns/\u0000$\u0008\u0001\u0012 Wi\ufffd{$\ufffd\u0017\u0000\ufffd[\ufffd)\ufffd\ufffdkԆ\ufffd%\ufffdϛq\ufffd\ufffd\ufffd\u000c\u001a\ufffd\ufffd\ufffd\u0006"}}
{"ts":1586971298427455018,"msg":"","group_id":"cypress-searcher","run_id":"13892111c6c8","event":{"type":"message","message":"Searching for IPNS Key: /ipns/\u0000$\u0008\u0001\u0012 \ufffd\ufffd\ufffd(\ufffdk\\P\ufffdb:!Z\ufffd\ufffd\ufffd\ufffd\u001d\u001a\u0008k\ufffdz\u0013\ufffd\ufffdʻl\ufffdj2"}}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 25176 [running]:
encoding/json.(*encodeState).marshal.func1(0xc0009f58d8)
        /usr/local/go/src/encoding/json/encode.go:305 +0x9a
panic(0xc990a0, 0x16b0f80)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/libp2p/go-libp2p-core/peer.AddrInfo.MarshalJSON(0xc0008ca9c0, 0x26, 0xc000d5ec40, 0x2, 0x2, 0xc0009f5650, 0x4ca4d1, 0xcc7de0, 0xc000a3e778, 0xc0009f5650)
        /go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.5.1/peer/addrinfo_serde.go:14 +0x18e
encoding/json.marshalerEncoder(0xc00030c540, 0xcc7de0, 0xc000a3e778, 0x196, 0xcc0000)
        /usr/local/go/src/encoding/json/encode.go:453 +0xc4
encoding/json.arrayEncoder.encode(0xf071d8, 0xc00030c540, 0xc35500, 0xc000490dc0, 0x97, 0x540000)
        /usr/local/go/src/encoding/json/encode.go:791 +0xd6
encoding/json.sliceEncoder.encode(0xc000bf2050, 0xc00030c540, 0xc35500, 0xc000490dc0, 0x97, 0xc30000)
        /usr/local/go/src/encoding/json/encode.go:765 +0x8f
encoding/json.(*encodeState).reflectValue(0xc00030c540, 0xc35500, 0xc000490dc0, 0x97, 0x0)
        /usr/local/go/src/encoding/json/encode.go:337 +0x82
encoding/json.(*encodeState).marshal(0xc00030c540, 0xc35500, 0xc000490dc0, 0x530000, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:309 +0x10b
encoding/json.(*Encoder).Encode(0xc000a3e780, 0xc35500, 0xc000490dc0, 0xdaa0b6, 0x4)
        /usr/local/go/src/encoding/json/stream.go:202 +0x8a
go.uber.org/zap/zapcore.(*jsonEncoder).AddReflected(0xc000e2e000, 0xdab8c1, 0x6, 0xc35500, 0xc000490dc0, 0xc000e2e000, 0x0)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/zapcore/json_encoder.go:150 +0x61
go.uber.org/zap/zapcore.Field.AddTo(0xdab8c1, 0x6, 0x16, 0x0, 0x0, 0x0, 0xc35500, 0xc000490dc0, 0x100bfe0, 0xc000e2e000)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/zapcore/field.go:159 +0xaf5
go.uber.org/zap/zapcore.addFields(0x100bfe0, 0xc000e2e000, 0xc000d1a780, 0x3, 0x6)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/zapcore/field.go:199 +0xcf
go.uber.org/zap/zapcore.(*jsonEncoder).EncodeEntry(0xc000e98ed0, 0x0, 0xbf9dee88a570c065, 0x5d11f262d1, 0x16ddce0, 0x0, 0x0, 0xdad69f, 0x7, 0x0, ...)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/zapcore/json_encoder.go:364 +0x1e4
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0009ff9b0, 0x0, 0xbf9dee88a570c065, 0x5d11f262d1, 0x16ddce0, 0x0, 0x0, 0xdad69f, 0x7, 0x0, ...)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/zapcore/core.go:86 +0xa9
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000d28160, 0xc000d1a780, 0x3, 0x6)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/zapcore/entry.go:216 +0x117
go.uber.org/zap.(*SugaredLogger).log(0xc00067e080, 0x0, 0xdad69f, 0x7, 0x0, 0x0, 0x0, 0xc0009f5f60, 0x6, 0x6)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Infow(...)
        /go/pkg/mod/go.uber.org/zap@v1.12.0/sugar.go:179
github.com/ipfs/testground/plans/dht/test.TraceQuery.func2(0xc000a6f560, 0xc00067e080)
        /plan/test/tracers.go:73 +0x1c6
created by github.com/ipfs/testground/plans/dht/test.TraceQuery
        /plan/test/tracers.go:56 +0x28d
```

**Comment by aschmahmann** [comment]
@nonsense any chance you have the testground logs from that run? Trying to figure out which sub test caused the error. It looks like somehow an `AddrInfo` struct was created with a list of addresses that contains a `nil`.

**Comment by nonsense** [comment]
Sorry, I don't have the logs from the run. Will make sure I recover more data if I notice this happening again!

**Comment by raulk** [comment]
Now that the DHT test plan doesn't live here any longer, this should be opened in github.com/libp2p/test-plans, with a link pointing here, and closed here. @Robmat05 -- can you take care of that?
